/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuroraBackground: typeof import('./../components/AuroraBackground.vue')['default']
    InteractiveGridPattern: typeof import('./../components/InteractiveGridPattern.vue')['default']
    LampEffect: typeof import('./../components/LampEffect.vue')['default']
    LiquidLogo: typeof import('./../components/LiquidLogo/index.vue')['default']
    ParentSize: typeof import('./../components/Spline/ParentSize.vue')['default']
    RainbowButton: typeof import('./../components/RainbowButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spline: typeof import('./../components/Spline/index.vue')['default']
    Vortex: typeof import('./../components/Vortex.vue')['default']
    WavyBackground: typeof import('./../components/WavyBackground.vue')['default']
  }
}
